[project]
name = "chest-x-ray-diagnosis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "hydra-core>=1.3.2",
    "mlflow>=2.20.3",
    "optuna>=4.2.1",
    "tensorflow>=2.18.0",
]
