
DATASET:
  DATASET_DIR: 'datasets'

DATASET_DIRS:
  IMAGES_DIR: ${DATASET.DATASET_DIR}/images-small/
  TRAIN_CSV: ${DATASET.DATASET_DIR}/train-small.csv
  VALID_CSV: ${DATASET.DATASET_DIR}/valid-small.csv
  TEST_CSV: ${DATASET.DATASET_DIR}/test.csv


PRETRAIN_MODEL:
  MODEL_NAME: 'ssd_resnet50_v1_fpn_640x640_coco17_tpu-8'
  PATH: 'pre-trained-models/${PRETRAIN_MODEL.MODEL_NAME}'

TRAIN:
  BATCH_SIZE: 32
  NUM_EPOCHS: 10
  LEARNING_RATE: 0.0001
  IMG_SIZE: 320

OUTPUTS:
  OUPUT_DIR: 'exported_models/my_${PRETRAIN_MODEL.MODEL_NAME}'
  CONFIG_PIPELINE_PATH: ${OUTPUTS.OUPUT_DIR}/
  CHECKPOINT_PATH: ${OUTPUTS.OUPUT_DIR}/checkpoints/

